import type { NextPage } from 'next';
import Head from 'next/head';
import useSWR from 'swr';

import API, { urls } from '../lib/API';

const Home: NextPage = () => {
  const { data, error } = useSWR(urls.TEST, API.get);

  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;
  if (data) console.log(data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Hello, World!</div>
    </div>
  );
};

export default Home;
