import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Therapistim</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>Hello, World!</div>

      <Link href='/profile'>
        <a>Profile</a>
      </Link>
    </div>
  );
};

export default Home;
